@startuml
'https://plantuml.com/sequence-diagram

autonumber

activate TraficManager
TraficManager -> system: select the borders import function
activate system

system --> TraficManager: informs success
deactivate system

deactivate TraficManager
@enduml